<?php

// USER ROLES
define('USER_ROLE_ADMIN', 0);
define('USER_ROLE_MANAGER', 1);
define('USER_ROLE_USER', 2);

// USER STATUSES
define('USER_STATUS_INACTIVE', 0);
define('USER_STATUS_ACTIVE', 1);

// INVITATION STATUSES
define('INVITATION_STATUS_PENDING', 0);
define('INVITATION_STATUS_VERIFYING', 1);
define('INVITATION_STATUS_COMPLETE', 2);

// CURRENCY TYPES
define('CURRENCY_TYPE_BTC', 0);
define('CURRENCY_TYPE_ETH', 1);
